### PR TITLE
Demo typos

### PR DESCRIPTION
**Pull request by agriffard**
Typo `Start and Eend slots` on https://www.fluentui-blazor.net/Toolbar#startandeendslots

Before:

image

After:

image

### CODE REVIEW

**Comment by dvoituron** [comment]
Thank you @agriffard for these clarifications in the documentation. It's always good to have the most correct documentation possible.

But can you make a single PR with all the bugs you find? That would make our lives easier, instead of creating one PR per label.

**Comment by agriffard** [comment]
> Thank you @agriffard for these clarifications in the documentation. It's always good to have the most correct documentation possible.
> 
> But can you make a single PR with all the bugs you find? That would make our lives easier, instead of creating one PR per label.

Ok, it is just because I stumbled upon it browsing the docs.

Keep this one open this weekend and if I find new ones, I'll add commits on it.

**Comment by agriffard** [comment]
https://www.fluentui-blazor.net/Header
https://www.fluentui-blazor.net/Footer
`component is used display` => component is used **to** display

**Comment by agriffard** [comment]
https://www.fluentui-blazor.net/Splitter

`arbitraty`=> arbitrary

**Comment by agriffard** [comment]
Replacing **it's** by **its** on multiple pages.

**Comment by agriffard** [comment]
Ok, it can be reviewed.

**Review by dvoituron — APPROVED** [review]

**Review by vnbaaij — APPROVED** [review]

**Pull request merged**
