### PR TITLE
Demo favicon

### PR DESCRIPTION
**Pull request by agriffard**
Add a favicon to the demo website:

image

image

Not sure if there is an official logo for the project but I created it based on this:
https://twitter.com/denisvoituron/status/1720377475882954986

favicon

### CODE REVIEW

**Comment by vnbaaij** [comment]
I really like this but before we can merge, could you make the light version to have:
1) The  F filled transparently (like the rest of the inside of the Blazor 'flame') 
or
2) have the rest of the inside of the Blazor flame be filled with white like the inside of the F

I think option 2 is better wrt the dark version. The having it all transparent would make the F kind of fade away I believe.

It is indeed our 'official' logo. There is also a png version available in the repository here. Maybe easier to work from that one.

**Comment by agriffard** [comment]
Option 1: As expected, transparency does not look good on dark.

image

image

Option 2: Filled with white (= the change I made).

image

image

**Comment by dvoituron** [comment]
For the Dark theme, I think a white icon would be better. We lose the colors, but it's probably better. No ?

Also for Accessibility rules.

**Comment by vnbaaij** [comment]
This is what you get in dark mode with the new Blazor Web App template: 
image
so a sort of white outline around it. Can we try that?

**Comment by agriffard** [comment]
I can do a .svg icon which is black on light mode and white on dark mode:

image

image
favicon

**Comment by dvoituron** [comment]
I prefer the solution proposed by Vincent 😊 Or only black/white for the Dark mode, but in colors for Light mode. 

I've a SVG file with the colored icon. I can give you that this evening.

**Comment by vnbaaij** [comment]
I like a purple variant better

**Comment by agriffard** [comment]
Version with white outline:

image

image

**Comment by vnbaaij** [comment]
Lgtm!

**Review by vnbaaij — APPROVED** [review]
Taking this in as-as for  now. We can fine tune later, if needed

**Comment by agriffard** [comment]
I replaced `favicon.ico` it `FluentUI.Demo.Server\wwwroot` when I tested locally but it seems the deployed website is `FluentUI.Demo.Client\wwwroot`.

The preview site https://black-pebble-0dc79cb03.3.azurestaticapps.net/ does not have the favicon.

Can you please make the change?

**Comment by vnbaaij** [comment]
I just pushed the changes to replace the favicon everywhere 15 minutes ago :). 

It is changed now: 
image

**Pull request merged**
