### PR TITLE
[Demo ] Add DataGridTableScroll demo

### PR DESCRIPTION
**Pull request by MarvinKlein1508**
# Pull Request

## 📖 Description

Added new DataGrid demo to show how to use "Table mode" on `FluentDataGrid` based on discussion #57820

fluentdatagrid-mobile

### CODE REVIEW

**Comment by dvoituron** [comment]
Could you add a screenshot in the PR description to simplify the future Release note?

**Comment by MarvinKlein1508** [comment]
@dvoituron I would but the app doesn't compile for me:
```
 build
1>> node ./esbuild.config.mjs
1>
1>file:///G:/Programmierung/fluentui-blazor/src/Core.Assets/esbuild.config.mjs:2
1>import pkg from './package.json' assert { type: 'json' }
1>                                 ^^^^^^
1>
1>SyntaxError: Unexpected identifier 'assert'
1>    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
1>    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:163:18)
1>    at callTranslator (node:internal/modules/esm/loader:430:14)
1>    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:436:30)
1>    at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)
1>
1>Node.js v22.2.0
```

I think I might have the wrong version of node. But couldn't find any info in the repo what I need to install for it.

**Comment by dvoituron** [comment]
Weird. This Node version seems enough. Are you using VS 2022 Preview? Or could tou run ˋnpm install` from the Assets project folder ?

**Comment by MarvinKlein1508** [comment]
@dvoituron I'm using VS 17.10.0

grafik

**Comment by dvoituron** [comment]
I'm also using this VS and Node 20.10.0 with the same `npm fund` result.
```
Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.10.0 Preview 7.0
```

The problem is probably elsewhere :-(

**Comment by MarvinKlein1508** [comment]
@dvoituron it is the nodeJS version. Downgrading to your version works fine for me. Here you go:
fluentdatagrid-desktop

fluentdatagrid-mobile

**Review by vnbaaij — APPROVED** [review]

**Comment by MarvinKlein1508** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
