### PR TITLE
fix: [FluentNavLink] An issue where empty strings were not allowed in Href

### PR DESCRIPTION
**Pull request by dannyldj**
# Pull Request

## 📖 Description

Fixed FluentNavLink not working correctly when Href was empty

## 👩‍💻 Reviewer Notes

So simple PR

## 📑 Test Plan

Verify that clicking on a FluentNavLink correctly navigates to the root page when the Href of the FluentNavLink is empty.

### General

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fluentui-blazor/blob/master/docs/contributing.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have added [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for my new component
- [ ] I have modified an existing component
- [ ] I have validated the [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for an existing component

### CODE REVIEW

**Review by vnbaaij — APPROVED** [review]

**Comment by vnbaaij** [comment]
There is a reason we do not want to have empty Hrefs. This is done on purpose so you can have entries in the FluentNavMenu that don't necessarily go somewhere but do invoke an action. Like in the https://www.fluentui-blazor.net/NavMenu#navigation-examples:

```
<FluentNavLink OnClick="OnClick" Icon="@(new Icons.Regular.Size20.LeafOne())">Item 3.1</FluentNavLink>
```

If you still need to have a link that goes to the homepage, you can use asa value either `"/"` or `"./"`. The latter can be used in case of using a proxy and using `PathBase`

**Comment by dannyldj** [comment]
The original NavLink component allows empty string. In addition, the link below recommends an empty string by moving to the root page.
[](https://learn.microsoft.com/ko-kr/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#navlink-component)

**Example**
```html
<div class="nav-scrollable" 
    onclick="document.querySelector('.navbar-toggler').click()">
    <nav class="flex-column">
        <div class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="bi bi-house-door-fill-nav-menu" 
                    aria-hidden="true"></span> Home
            </NavLink>
        </div>

+       @foreach (var name in GetRoutableComponents())
+       {
+           <div class="nav-item px-3">
+               <NavLink class="nav-link" 
+                       href="@Regex.Replace(name, @"(\B[A-Z]|\d+)", "-$1").ToLower()">
+                   @Regex.Replace(name, @"(\B[A-Z]|\d+)", " $1")
+               </NavLink>
+           </div>
+       }

    </nav>
</div>
```

**Comment by dannyldj** [comment]
The original NavLink component allows empty string. In addition, the link below recommends an empty string by moving to the root page.
[](https://learn.microsoft.com/ko-kr/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#navlink-component)

**Example**
```html
<div class="nav-scrollable" 
    onclick="document.querySelector('.navbar-toggler').click()">
    <nav class="flex-column">
        <div class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="bi bi-house-door-fill-nav-menu" 
                    aria-hidden="true"></span> Home
            </NavLink>
        </div>

+       @foreach (var name in GetRoutableComponents())
+       {
+           <div class="nav-item px-3">
+               <NavLink class="nav-link" 
+                       href="@Regex.Replace(name, @"(\B[A-Z]|\d+)", "-$1").ToLower()">
+                   @Regex.Replace(name, @"(\B[A-Z]|\d+)", " $1")
+               </NavLink>
+           </div>
+       }

    </nav>
</div>
```

Since that property is nullable, it will work as intended, as long as you don't make the stupid mistake of declaring the Href to be an empty string and throwing in an OnClick callback.

**Comment by vnbaaij** [comment]
Tested on the `NavMenuDefault` example and it indeed works as expected. Merging it in. Thanks!

**Pull request merged**
