### PR TITLE
Enhance FluentAccordionItem with Flexible HeadingContent Parameter

### PR DESCRIPTION
**Pull request by LuohuaRain**
# Pull Request

## 📖 Description
image

I've updated the `FluentAccordionItem` component to enhance its flexibility and usability. Previously, attempting to control the heading slot resulted in a RZ2012 error. To address this issue, I've made the following changes:

1. Removed the `EditorRequiredAttribute` to avoid the RZ2012 error.
2. Introduced a new `RenderFragment?` parameter, `HeadingContent`, providing an alternative way to specify the heading content. This addition allows users to define custom heading content more flexibly.

### General

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fluentui-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have added [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for my new compontent
- [x] I have modified an existing component
- [x] I have validate [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for an existing component

### CODE REVIEW

**Comment by dvoituron** [comment]
Thank you for this useful improvement.
Can you fix the unit tests that no longer work?
And add a test to validate the use of `HeadingContent`?

**Comment by LuohuaRain** [comment]
> Thank you for this useful improvement. Can you fix the unit tests that no longer work? And add a test to validate the use of `HeadingContent`?

Of course, I'll give a try. 😊

**Comment by LuohuaRain** [comment]
Hi,
I've just pushed some commits related to unit testing. As this is my initial attempt at writing unit tests (bUnit), there might be areas for improvement. I would greatly appreciate your feedback and suggestions to enhance the quality of these tests.

Thank you🚀

**Comment by vnbaaij** [comment]
I'm looking at the tests now. So far, looking good!
Can you please rename the `HeaderContent` name to `HeaderTemplate`. That is more consistent with how we do it in other places in the library. Also, add in the XML comments only one should be used and which one takes precedence if someone does use both.

**Review by vnbaaij — APPROVED** [review]
Ok, we are taking the the PR as-is and change the parameter name ourselves. Thanks!!

**Comment by LuohuaRain** [comment]
Sorry, due to the time difference, I went out for dinner, and it took some time. Apologies.😭

**Comment by vnbaaij** [comment]
No worries!! Hope you had a nice dinner. Thanks for making the initial changes. Getting it aligned to our naming is only a small change.

**Pull request merged**
