### PR TITLE
Template updates

### PR DESCRIPTION
**Pull request by c0g1t8**
# Pull Request

## 📖 Description

When creating a new fluent ui wasm project, _FetchData.razor_ page generates nullable warnings on compile.

### 🎫 Issues

Warnings generated from code created from template.

``` powershell
Build started...
1>------ Build started: Project: fluentwasm, Configuration: Debug Any CPU ------
1>C:\git\fluentwasm\Pages\FetchData.razor(17,55,17,56): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(18,60,18,61): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(19,60,19,61): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(20,58,20,59): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(25,41,25,50): warning CS8618: Non-nullable field 'forecasts' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
1>C:\git\fluentwasm\Pages\FetchData.razor(17,55,17,56): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(18,60,18,61): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(19,60,19,61): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(20,58,20,59): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(25,41,25,50): warning CS8618: Non-nullable field 'forecasts' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
1>fluentwasm -> C:\git\fluentwasm\bin\Debug\net7.0\fluentwasm.dll
1>fluentwasm (Blazor output) -> C:\git\fluentwasm\bin\Debug\net7.0\wwwroot
1>Done building project "fluentwasm.csproj".
1>fluentwasm -> C:\git\fluentwasm\bin\Debug\net6.0\fluentwasm.dll
1>fluentwasm (Blazor output) -> C:\git\fluentwasm\bin\Debug\net6.0\wwwroot
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 1:58 PM and took 11.658 seconds ==========
```

### General

- [ ] I have added tests for my changes.
- [X] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [X] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component

### CODE REVIEW

**Review by vnbaaij — COMMENTED** [review]
Can you do this for Server version as well?

**Comment by vnbaaij** [comment]
Great, I'll merge it in once done. Thanks for your contribution!

**Comment by c0g1t8** [comment]
@vnbaaij 

I also noticed in the *.csproj files
```
	<ItemGroup>
		<PackageReference Include="Microsoft.Fast.Components.FluentUI" Version="2.1.*" />
	</ItemGroup>
```
shouldn't this also be upgraded to 
```
	<ItemGroup>
		<PackageReference Include="Microsoft.Fast.Components.FluentUI" Version="2.3.*" />
	</ItemGroup>
```

**Comment by vnbaaij** [comment]
Yeah, that would be better indeed

**Comment by c0g1t8** [comment]
> Yeah, that would be better indeed. Another commit?

Updated templates to use 2.3.*

**Pull request merged**
