### PR TITLE
[Button] Add StopPropagation + UnitTests

### PR DESCRIPTION
**Pull request by vnbaaij**
Adds `StopPropagation` parameter to `FluentButton` top prevent click for bubbling up to parent elements.

2 tests added to confirm it works as expected

### CODE REVIEW

**Comment by dvoituron** [comment]
Wr could add a tag `v5` to avoid to forget new features in existing components in v5 lib? Maybe also to forward these changes to `dev-v5`

**Review by dvoituron — APPROVED** [review]

**Comment by vnbaaij** [comment]
> Wr could add a tag `v5` to avoid to forget new features in existing components in v5 lib? Maybe also to forward these changes to `dev-v5`

We have the vNext label. I added it to this PR, just as we do with the issues.

**Comment by vnbaaij** [comment]
V5 PR created as well (#2733)

**Comment by oerbeke** [comment]
Have nothing to add, just want to say thank you for this addition. Have had problems with event propagation :)

**Pull request merged**
