### PR TITLE
feat: allow the ability to hide the dismissal button for the FluentMessageBar.

### PR DESCRIPTION
**Pull request by StevenRasmussen**
# Pull Request

## 📖 Description

Adds the `AllowDismiss` property to the `FluentMessageBar` component.  Sometimes it would be beneficial to have a message bar displayed that is not dismissible by the user.  This adds the property and sets the default to `true` so that existing instances do not break.  I added another `FluentMessageBar` instance under the `MessageBarSimple` example to demonstrate the behavior and for documentation.

### General

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fluentui-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have added [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for my new compontent
- [x] I have modified an existing component
- [ ] I have validate [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for an existing component

### CODE REVIEW

**Comment by vnbaaij** [comment]
Hi Steven, Thanks for this.
Before we can merge, please make sure the existing Unit Tests validate (pretty sure it will fial now with AllowDissmiss=false) and add some new Unit Tests to test this new behavior

**Comment by dvoituron** [comment]
I find this improvement interesting.
Could you include a screenshot of this new "design" in your PR, to check if the UI rules are respected?

**Comment by StevenRasmussen** [comment]
Here is a screenshot of the demo app:
image

It appears to honor the UI rules and allows the content to fill up the entire space now.  I'll take a look at the unit tests to see what needs to be updated there.  Thanks for the consideration.

**Comment by StevenRasmussen** [comment]
I added another unit test for this new property.  The existing unit test was still succeeding (as it should) since this property does not affect existing instances with the default set to `true`.  Please let me know if you need anything else to complete this PR.

**Review by vnbaaij — APPROVED** [review]

**Review by dvoituron — APPROVED** [review]

**Pull request merged**
