### PR TITLE
[DataGrid] Make `Grid` in `ColumnBase` public again

### PR DESCRIPTION
**Pull request by vnbaaij**
Title says it all

### CODE REVIEW

**Comment by dvoituron** [comment]
Why do we need to set `public`? Can we set `protected` ?

**Comment by vnbaaij** [comment]
When devs want to create their own custom column (derived from ColumnBase), they need to be able to access the Grid parameter.

**Comment by liaan-mynhardt** [comment]
I have another use case for Grid to be public. If I wanted to create a reusable column header component that I pass in using HeaderCellItemTemplate I can do so using the "context" parameter eg. 
`<CustomizableDataGridColumnHeader Column="context" />`
by changing it to protected I will have to do 
`<CustomizableDataGridColumnHeader Grid="topGrid" Column="context" />`
which opens me up to passing in the wrong grid reference.
Thoughts?

**Comment by vnbaaij** [comment]
I can live with that,

Protected is meant for giving access for derived classes so it covers the use case well. Dev should be able to spot/fix easily

**Comment by aDisplayName** [comment]
> When devs want to create their own custom column (derived from ColumnBase), they need to be able to access the Grid parameter. Protected should suffice for that as well yes. Will change.

Oh god, it just broken our existing code......

**Comment by vnbaaij** [comment]
> Oh god, it just broken our existing code......

Take a look at how it is done in the Aspire repo. They have created their own `PropertyColumn` and `TemplateColumn` implementations with Grid being protected.

**Pull request merged**
