### PR TITLE
[Demo] Fixes link for Time picker in demo projects

### PR DESCRIPTION
**Pull request by MarvinKlein1508**
# Pull Request

## 📖 Description

this PR removes the fragment from the demo navigation for the `/DateTime` link. 

### General

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fluentui-blazor/blob/master/docs/contributing.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by vnbaaij — CHANGES_REQUESTED** [review]
I don't think the fragment should be removed. It just needs to point to the default time picker example on that page.

**Comment by MarvinKlein1508** [comment]
@vnbaaij I removed it since all other components don't have one as well. It would be strange to start the page right in the middle since there is no nav item for FluentDatePicker

**Comment by vnbaaij** [comment]
Yes, it is strange but even stranger to click on a link to time picker and land on a date picker segment 😀.

Time picker is an InputBase derived component. That is why it is shown in Form and input menu. DatePicker is not InputBase derived (yet?). 

We need to address the underlying issue and probably just make separate pages.

**Comment by MarvinKlein1508** [comment]
Got it. Added the fragment. I didn't even know that you can find the FluentDatePicker under components instead.

**Review by vnbaaij — APPROVED** [review]

**Pull request merged**
