### PR TITLE
Add Orientation support for FluentLayout

### PR DESCRIPTION
**Pull request by StevenTCramer**
# Pull Request

## 📖 Description

FluentLayout is flex column.  This PR adds the ability to have this flex row or flex column

### 🎫 Issues

No found.

## 👩‍💻 Reviewer Notes

The default stays the same as the current.  So this won't be a breaking change.

## 📑 Test Plan

Added Buint tests for FluentLayout.

image

### General

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fluentui-blazor/blob/master/docs/contributing.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have added [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for my new compontent
- [x] I have modified an existing component
- [x] I have validated the [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for an existing component

### CODE REVIEW

**Review by vnbaaij — CHANGES_REQUESTED** [review]
Can you change this to like I've done this for the recent change in Fluent Input Label. With an attribute instead of new class. See #1994. 
Let me know if it is unclear what I mean. Thanks

**Comment by StevenTCramer** [comment]
Done and added BUnit tests also.

**Comment by dvoituron** [comment]
What is the goal of this new `Orientation` attribute? Could you add a screenshot of the two cases to explain?

**Comment by StevenTCramer** [comment]
If you have fixed full width header on a page you would likely want flex column.
image

If you have a fixed sidebar on a page you would likely want flex row.

image

**Comment by dvoituron** [comment]
Mmmm. OK. This could be solved very easily with a style, but why not add this attribute. Thanks.

**Review by dvoituron — APPROVED** [review]

**Review by vnbaaij — APPROVED** [review]

**Pull request merged**
