### PR TITLE
[Demo & docs] Clears demo site cache on startup if new version

### PR DESCRIPTION
**Pull request by c0g1t8**
# Pull Request

## 📖 Description

Clears the browser cache when the demo site is started. 

### 🎫 Issues

Old versions of the markdown are retained between sessions. So when a new version of the site is released, new markdown content will not be downloaded if an older version is cached.

For example, the WhatsNew page continues to render previous version.

## 👩‍💻 Reviewer Notes

I've made the CacheStorageAccessor a singleton and provided a flag to check if the cache has been previously cleared.

I would have preferred being to _tag_ the cache but was not sure if the extra effort was necessary. That way, the cache would only be cleared if there is a new version or build.  Thoughts?

### General

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [X] I have read the [CONTRIBUTING](https://github.com/Microsoft/fluentui-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by dvoituron — APPROVED** [review]

**Comment by vnbaaij** [comment]
In the `CacheStorageAccessor.js` script, I 'put' the responses with a cache duration (7 days) and chechk the validity on the 'get' action. Wouldn't this change make that part a bit useless then? As everything gets cleared out when the site is restarted anyway.
Maybe we should just shorthen the cache duration (to 2 or 3 days)?

**Comment by c0g1t8** [comment]
> In the `CacheStorageAccessor.js` script, I 'put' the responses with a cache duration (7 days) and chechk the validity on the 'get' action. Wouldn't this change make that part a bit useless then? As everything gets cleared out when the site is restarted anyway. Maybe we should just shorthen the cache duration (to 2 or 3 days)?

Shortening the cache time will still result in the user getting old information for several days after a new release. I'm thinking in the case of breaking changes.  

The best solution would be to _tag_ the cache with the version and build information (_Version: 4.6.1+ff23edc6_). Check to see if there is a match and only flush the cache if they dont' match.

The plan would be to implement a new service that returns the current build information and inject it into `CacheStorageAccessor`. Thoughts?

**Comment by vnbaaij** [comment]
Yes, that sounds like a good plan. Tagging each item is the way to go, I think

**Comment by c0g1t8** [comment]
@vnbaaij 

I put a file in the cache ('appVersion') with the version corresponding to the files cached. I used the same version string as that shown in the footer of the demo site. When this version is updated, all files cached are considered stale and removed.

**Comment by c0g1t8** [comment]
Changing status back to draft. I accidentally reverted something. 😒

**Review by vnbaaij — APPROVED** [review]

**Pull request merged**
