### PR TITLE
[DataGrid] Row Additional Content

### PR DESCRIPTION
**Pull request by franklupo**
Ability to add additional content to DataGrid row, with check if add.
Original PR #2389

### CODE REVIEW

**Comment by franklupo** [comment]
something is missing?

**Comment by franklupo** [comment]
Are there any problems applying this change?

**Comment by vnbaaij** [comment]
Hi Daniele, still not have time to take a proper look at this and won't be able for the coming weeks because of vacation period. There is no rush to get this in as it will require at least a minor release (i.e. 4.X)

**Comment by franklupo** [comment]
you're right, this change gives me the ability to create components outside of this library.

**Comment by vnbaaij** [comment]
Closing this as there has been no activity for a while.

**Pull request closed without merging**
