### PR TITLE
[Package versions] Refactoring

### PR DESCRIPTION
**Pull request by dvoituron**
# [Package versions] Refactoring

- Set package versions to stable versions. Except for `Microsoft.CodeAnalysis.Analyzers` where the latest stable version is 3 years old.
- Consider all Warnings like Errors, during the build process: `-warnaserror`
- Update C# code to respect the Analyzer (missing `Async`).

### CODE REVIEW

**Review by vnbaaij — APPROVED** [review]

**Comment by vnbaaij** [comment]
The latest coverlet and Markdig are not available in dotnet-public feed.

**Comment by dvoituron** [comment]
Why do we need to use this feed and not NuGet.org?

**Comment by vnbaaij** [comment]
Requirements of the 1ES templates/security initiative.

**Comment by dvoituron** [comment]
Ok. I will update that.

**Pull request merged**
