### PR TITLE
Make NavGroup work with enhanced navigation and SSR

### PR DESCRIPTION
**Pull request by aco-mreble**
# Pull Request

## 📖 Description
This pull request has cost me some time as I had to really dig into Blazors documentation. As the `Nav...` components are not in the javascript fluent-ui repo I had to find a way how to handle navigations in the new Blazor 8 SSR with Enhanced Navigation enabled. 

I had to add a new Component (I am not sure if it lies in the right directory) called `PageScript` and I had to add code to the `index.ts` file as descriped in the [microsoft docs](https://learn.microsoft.com/en-US/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0)

I think this feature can help us a lot in the future as we now have the possiblity to listen to `onLoad`, `onUpdated` and `onDisposed` when SSR and enhanced navigation is enabled. While testing I found some other bugs e.g. in the `TreeView` - I will create a Issue for that in the future

## 👩‍💻 Reviewer Notes
Please dig a little bit deeper to Blazor 8 with me on this Pull Request. I am also open to have a short call about the changes made here if there are any questions open, I am at the FAST Discord called SCSpider.

Please bear with me, I am not a javascript/typescript developer so I am not sure if that is actually the best solution.

For testing you can use my demo project: https://github.com/aco-mreble/fluentui-blazor-ssr-demo

Initial Issue: https://github.com/microsoft/fluentui-blazor/issues/1105

## 📑 Test Plan
Added `page-script` element to `.verified.html` files

### General

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fluentui-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have added [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for my new compontent
- [x] I have modified an existing component
- [x] I have validate [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for an existing component

### CODE REVIEW

**Review by vnbaaij — APPROVED** [review]
This is great! It will need a couple of tweaks* after merge but I will do those. Thanks!

*) Don't think `Utilities` is the best blace for the `PageScript` component as we have no components in there. Also, there are some change needed in the `index.ts` script

**Comment by vnbaaij** [comment]
@aco-mreble Max, I worked on the script a bit more...Think I have all the interactions now as they should be. In gif below first part is mouse interaction, seconf part (when the black squares appear is keyboard interaction.
Also, moved the PageScript call to `FluentNavMenu` component (so gets inserted fewer times) and made the script itself trigger on `onUpdate` (instead of `onLoad`). Will abe in 4.2.1 release which I'm about to start building any minute now...

navmenu-ssr

**Comment by aco-mreble** [comment]
Great, lgtm! Thanks for your super fast response time! :)

**Comment by aco-mreble** [comment]
@vnbaaij  Found out that the `page-script` element should have css `display:none;` so it won't interfeere with e.g. `display: flex; justify-content: space-between;` for the parent element

**Comment by vnbaaij** [comment]
@aco-mreble Hi Max. I'll add that. Good catch!

**Pull request merged**
